### ISSUE TITLE
What is map.csv w.r.t. CheXpert?

### ISSUE THREAD

**Issue by basedrhys** [MLforHealth/ClinicalDG#1]
Hi,

I'm trying to replicate your results and am setting up the datasets, however, am confused about the `map.csv` file referenced in the validation/preprocessing scripts for CheXpert.

In CheXpert I only have `train.csv` and `valid.csv`, not `map.csv`. What is this file? Is it a concatenation of `train.csv` and `valid.csv`? Alternatively, can you link to the `map.csv` file you used in your experiments?

Thanks!

**Comment by hzhang0** [comment]
Thanks for pointing this out! You are right that it is simply the concatenation of `train.csv` and `test.csv`. I have fixed this in the latest commit (72154a87a6d36416c0dac36e7a846b1194c7f39c). Sorry for the inconvenience, and let me know if you run into any other issues.
